#!/usr/bin/env bash
export SCRIPTPATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

#start network manager applet
if [ -x "$(command -v nm-applet)"]; then
  nm-applet &
fi

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#boot picom or compton if it exists
#this is for windows animations, fades etc.
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

index=0
monitors=$(polybar -m | awk '{ split($1,a,":"); print(a[1]) }')
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y; do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<< "$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar $barname &> /dev/null &
  let index=indextemp
done

if [ -x "$(command -v xscreensaver)" ]; then
  xscreensaver -no-splash &
fi

if [ -x "$(command -v polkit-dumb-agent)" ]; then
  polkit-dumb-agent &
fi

if [ -x "$(command -v dunst)" ]; then
  cp $SCRIPTPATH/dunstrc ~/.config/dunst/dunstrc
  dunst &
fi
